// <auto-generated />
using System;
using Lamour.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Lamour.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260613041536_SalesReturnCreate")]
    partial class SalesReturnCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Lamour.Domain.Entities.CashTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Account")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("account");

                    b.Property<DateTime>("AccountingDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accounting_date");

                    b.Property<string>("CounterAccount")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("counter_account");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("CreditAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("credit_amount");

                    b.Property<decimal>("DebitAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("debit_amount");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<DateTime>("DocumentDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("document_date");

                    b.Property<string>("PaymentNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("payment_number");

                    b.Property<string>("PersonName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("person_name");

                    b.Property<string>("ReceiptNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("receipt_number");

                    b.HasKey("Id");

                    b.HasIndex("AccountingDate");

                    b.ToTable("cash_transactions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Account = "111",
                            AccountingDate = new DateTime(2023, 11, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CounterAccount = "131",
                            CreatedAt = new DateTime(2023, 11, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreditAmount = 0m,
                            DebitAmount = 520000m,
                            Description = "Thu tiền khách hàng",
                            DocumentDate = new DateTime(2023, 11, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            PersonName = "Thanh Đức",
                            ReceiptNumber = "PT00678"
                        },
                        new
                        {
                            Id = 2,
                            Account = "111",
                            AccountingDate = new DateTime(2023, 11, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CounterAccount = "131",
                            CreatedAt = new DateTime(2023, 11, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreditAmount = 0m,
                            DebitAmount = 5850000m,
                            Description = "Thu tiền khách hàng",
                            DocumentDate = new DateTime(2023, 11, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            PersonName = "Thanh Đức",
                            ReceiptNumber = "PT00678"
                        },
                        new
                        {
                            Id = 3,
                            Account = "111",
                            AccountingDate = new DateTime(2023, 11, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CounterAccount = "131",
                            CreatedAt = new DateTime(2023, 11, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreditAmount = 0m,
                            DebitAmount = 5025000m,
                            Description = "Thu tiền khách hàng",
                            DocumentDate = new DateTime(2023, 11, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            PersonName = "Thanh Đức",
                            ReceiptNumber = "PT00678"
                        },
                        new
                        {
                            Id = 4,
                            Account = "111",
                            AccountingDate = new DateTime(2023, 11, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CounterAccount = "131",
                            CreatedAt = new DateTime(2023, 11, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreditAmount = 0m,
                            DebitAmount = 5640000m,
                            Description = "Thu tiền khách hàng",
                            DocumentDate = new DateTime(2023, 11, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            PersonName = "Thanh Đức",
                            ReceiptNumber = "PT00678"
                        },
                        new
                        {
                            Id = 5,
                            Account = "111",
                            AccountingDate = new DateTime(2023, 11, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CounterAccount = "131",
                            CreatedAt = new DateTime(2023, 11, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreditAmount = 0m,
                            DebitAmount = 5200000m,
                            Description = "Thu tiền khách hàng",
                            DocumentDate = new DateTime(2023, 11, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            PersonName = "Thanh Đức",
                            ReceiptNumber = "PT00678"
                        },
                        new
                        {
                            Id = 6,
                            Account = "111",
                            AccountingDate = new DateTime(2023, 11, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CounterAccount = "6418",
                            CreatedAt = new DateTime(2023, 11, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreditAmount = 615000m,
                            DebitAmount = 0m,
                            Description = "Diễm",
                            DocumentDate = new DateTime(2023, 11, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            PaymentNumber = "PC02215",
                            PersonName = "LÊ HOÀNG THANH ĐỨC"
                        },
                        new
                        {
                            Id = 7,
                            Account = "111",
                            AccountingDate = new DateTime(2023, 11, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CounterAccount = "6418",
                            CreatedAt = new DateTime(2023, 11, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreditAmount = 1055000m,
                            DebitAmount = 0m,
                            Description = "Thảo Uyên",
                            DocumentDate = new DateTime(2023, 11, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            PaymentNumber = "PC02215",
                            PersonName = "LÊ HOÀNG THANH ĐỨC"
                        },
                        new
                        {
                            Id = 8,
                            Account = "111",
                            AccountingDate = new DateTime(2023, 11, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CounterAccount = "6418",
                            CreatedAt = new DateTime(2023, 11, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreditAmount = 1228000m,
                            DebitAmount = 0m,
                            Description = "Phúc Nhi",
                            DocumentDate = new DateTime(2023, 11, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            PaymentNumber = "PC02215",
                            PersonName = "LÊ HOÀNG THANH ĐỨC"
                        },
                        new
                        {
                            Id = 9,
                            Account = "111",
                            AccountingDate = new DateTime(2023, 11, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CounterAccount = "6418",
                            CreatedAt = new DateTime(2023, 11, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreditAmount = 174000m,
                            DebitAmount = 0m,
                            Description = "Hân",
                            DocumentDate = new DateTime(2023, 11, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            PaymentNumber = "PC02215",
                            PersonName = "LÊ HOÀNG THANH ĐỨC"
                        },
                        new
                        {
                            Id = 10,
                            Account = "111",
                            AccountingDate = new DateTime(2023, 11, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CounterAccount = "6418",
                            CreatedAt = new DateTime(2023, 11, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreditAmount = 105000m,
                            DebitAmount = 0m,
                            Description = "Hương Ly",
                            DocumentDate = new DateTime(2023, 11, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            PaymentNumber = "PC02215",
                            PersonName = "LÊ HOÀNG THANH ĐỨC"
                        },
                        new
                        {
                            Id = 11,
                            Account = "111",
                            AccountingDate = new DateTime(2023, 11, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CounterAccount = "6418",
                            CreatedAt = new DateTime(2023, 11, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreditAmount = 450000m,
                            DebitAmount = 0m,
                            Description = "Mua like fanpage tháng 10/2023",
                            DocumentDate = new DateTime(2023, 11, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            PaymentNumber = "PC02216",
                            PersonName = "NGUYỄN HÀ THANH HÀ"
                        },
                        new
                        {
                            Id = 12,
                            Account = "111",
                            AccountingDate = new DateTime(2023, 11, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CounterAccount = "6418",
                            CreatedAt = new DateTime(2023, 11, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreditAmount = 1715000m,
                            DebitAmount = 0m,
                            Description = "Phí lưu kho t10/2023",
                            DocumentDate = new DateTime(2023, 11, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            PaymentNumber = "PC02217",
                            PersonName = "LÊ HOÀNG THANH ĐỨC"
                        },
                        new
                        {
                            Id = 13,
                            Account = "111",
                            AccountingDate = new DateTime(2023, 11, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CounterAccount = "6418",
                            CreatedAt = new DateTime(2023, 11, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreditAmount = 40000000m,
                            DebitAmount = 0m,
                            Description = "Thuê VP t11/2023",
                            DocumentDate = new DateTime(2023, 11, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            PaymentNumber = "PC02218",
                            PersonName = "LÊ HOÀNG THANH ĐỨC"
                        });
                });

            modelBuilder.Entity("Lamour.Domain.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("address");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<string>("CustomerGroup")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("customer_group");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("province");

                    b.Property<string>("SaleCare")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("sale_care");

                    b.Property<string>("TaxCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tax_code");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("customers", (string)null);
                });

            modelBuilder.Entity("Lamour.Domain.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BankAccountNumber")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("bank_account_number");

                    b.Property<string>("BankName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("bank_name");

                    b.Property<string>("Code")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("")
                        .HasColumnName("code");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("job_title");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("unit");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("employees", (string)null);
                });

            modelBuilder.Entity("Lamour.Domain.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AccountingDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Attachment")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DocumentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PayeeName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("PaymentEmployeeId")
                        .HasColumnType("integer");

                    b.Property<string>("PaymentReason")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Reference")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("SupplierId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PaymentEmployeeId");

                    b.HasIndex("SupplierId");

                    b.ToTable("payments", (string)null);
                });

            modelBuilder.Entity("Lamour.Domain.Entities.PaymentEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("BankAccount")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CreditAccount")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("DebitAccount")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("PaymentId")
                        .HasColumnType("integer");

                    b.Property<string>("SubjectCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SubjectName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("PaymentId");

                    b.ToTable("payment_entries", (string)null);
                });

            modelBuilder.Entity("Lamour.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<decimal>("CostPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("cost_price");

                    b.Property<string>("ExciseTaxGroup")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("excise_tax_group");

                    b.Property<decimal?>("ExportTaxRate")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("export_tax_rate");

                    b.Property<decimal?>("ImportTaxRate")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("import_tax_rate");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<decimal>("SellingPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("selling_price");

                    b.Property<int>("StockQuantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("stock_quantity");

                    b.Property<string>("TaxReductionType")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tax_reduction_type");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("unit");

                    b.Property<string>("VatRate")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("vat_rate");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasFilter("code <> ''");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("Lamour.Domain.Entities.Receipt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AccountingDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Attachment")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("CollectorEmployeeId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DocumentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PayerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PaymentReason")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Reference")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("CollectorEmployeeId");

                    b.HasIndex("CustomerId");

                    b.ToTable("receipts", (string)null);
                });

            modelBuilder.Entity("Lamour.Domain.Entities.ReceiptEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("BankAccount")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CreditAccount")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("DebitAccount")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("ReceiptId")
                        .HasColumnType("integer");

                    b.Property<string>("SubjectCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SubjectName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ReceiptId");

                    b.ToTable("receipt_entries", (string)null);
                });

            modelBuilder.Entity("Lamour.Domain.Entities.SalesOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AccountingDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accounting_date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer")
                        .HasColumnName("customer_id");

                    b.Property<string>("DeliveryMethod")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("delivery_method");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<DateTime>("DocumentDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("document_date");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("document_number");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("integer")
                        .HasColumnName("employee_id");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<DateTime?>("PaymentDueDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("payment_due_date");

                    b.Property<int?>("PaymentDueDays")
                        .HasColumnType("integer")
                        .HasColumnName("payment_due_days");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("payment_method");

                    b.Property<string>("PaymentTerms")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("payment_terms");

                    b.Property<string>("Reference")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("reference");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("status");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total_amount");

                    b.HasKey("Id");

                    b.HasIndex("AccountingDate");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DocumentNumber")
                        .IsUnique();

                    b.HasIndex("EmployeeId");

                    b.ToTable("sales_orders", (string)null);
                });

            modelBuilder.Entity("Lamour.Domain.Entities.SalesOrderLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<decimal>("DiscountRate")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("discount_rate");

                    b.Property<bool>("IsPromotion")
                        .HasColumnType("boolean")
                        .HasColumnName("is_promotion");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("product_code");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("product_name");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<string>("ReceivableAccount")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("receivable_account");

                    b.Property<string>("RevenueAccount")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("revenue_account");

                    b.Property<int>("SalesOrderId")
                        .HasColumnType("integer")
                        .HasColumnName("sales_order_id");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("unit");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("unit_price");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("SalesOrderId");

                    b.ToTable("sales_order_lines", (string)null);
                });

            modelBuilder.Entity("Lamour.Domain.Entities.SalesReturn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AccountingDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accounting_date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer")
                        .HasColumnName("customer_id");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<DateTime>("DocumentDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("document_date");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("document_number");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("integer")
                        .HasColumnName("employee_id");

                    b.Property<string>("Reference")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("reference");

                    b.Property<int>("ReturnType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("return_type");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total_amount");

                    b.Property<decimal>("TotalDiscount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total_discount");

                    b.Property<decimal>("TotalPayment")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total_payment");

                    b.HasKey("Id");

                    b.HasIndex("AccountingDate");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DocumentNumber")
                        .IsUnique();

                    b.HasIndex("EmployeeId");

                    b.ToTable("sales_returns", (string)null);
                });

            modelBuilder.Entity("Lamour.Domain.Entities.SalesReturnLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<string>("DebtAccount")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("debt_account");

                    b.Property<string>("DiscountAccount")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("discount_account");

                    b.Property<decimal>("DiscountAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("discount_amount");

                    b.Property<decimal>("DiscountRate")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("discount_rate");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("product_code");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("product_name");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<string>("ReturnAccount")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("return_account");

                    b.Property<string>("SalesOrderNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("sales_order_number");

                    b.Property<int>("SalesReturnId")
                        .HasColumnType("integer")
                        .HasColumnName("sales_return_id");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("unit");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("unit_price");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("SalesReturnId");

                    b.ToTable("sales_return_lines", (string)null);
                });

            modelBuilder.Entity("Lamour.Domain.Entities.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("address");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("group");

                    b.Property<bool>("IsStopTracking")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_stop_tracking");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<string>("TaxCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tax_code");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("suppliers", (string)null);
                });

            modelBuilder.Entity("Lamour.Domain.Entities.Warehouse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("warehouses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "KHO01",
                            IsActive = true,
                            Name = "Kho chính"
                        });
                });

            modelBuilder.Entity("Lamour.Domain.Entities.WarehouseReceipt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AccountingDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accounting_date");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("integer")
                        .HasColumnName("customer_id");

                    b.Property<string>("DeliveryPerson")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("delivery_person");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("description");

                    b.Property<DateTime>("DocumentDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("document_date");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("integer")
                        .HasColumnName("employee_id");

                    b.Property<string>("ReceiptNumber")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("receipt_number");

                    b.Property<int>("ReceiptType")
                        .HasColumnType("integer")
                        .HasColumnName("receipt_type");

                    b.Property<string>("Reference")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("reference");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total_amount");

                    b.HasKey("Id");

                    b.HasIndex("AccountingDate");

                    b.HasIndex("CustomerId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("Status");

                    b.ToTable("warehouse_receipts", (string)null);
                });

            modelBuilder.Entity("Lamour.Domain.Entities.WarehouseReceiptLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<string>("CreditAccount")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("credit_account");

                    b.Property<string>("DebitAccount")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("debit_account");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("unit_price");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("integer")
                        .HasColumnName("warehouse_id");

                    b.Property<int>("WarehouseReceiptId")
                        .HasColumnType("integer")
                        .HasColumnName("warehouse_receipt_id");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("WarehouseId");

                    b.HasIndex("WarehouseReceiptId");

                    b.ToTable("warehouse_receipt_lines", (string)null);
                });

            modelBuilder.Entity("Lamour.Domain.Entities.Payment", b =>
                {
                    b.HasOne("Lamour.Domain.Entities.Employee", "PaymentEmployee")
                        .WithMany()
                        .HasForeignKey("PaymentEmployeeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Lamour.Domain.Entities.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PaymentEmployee");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("Lamour.Domain.Entities.PaymentEntry", b =>
                {
                    b.HasOne("Lamour.Domain.Entities.Payment", "Payment")
                        .WithMany("Entries")
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("Lamour.Domain.Entities.Receipt", b =>
                {
                    b.HasOne("Lamour.Domain.Entities.Employee", "CollectorEmployee")
                        .WithMany()
                        .HasForeignKey("CollectorEmployeeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Lamour.Domain.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CollectorEmployee");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Lamour.Domain.Entities.ReceiptEntry", b =>
                {
                    b.HasOne("Lamour.Domain.Entities.Receipt", "Receipt")
                        .WithMany("Entries")
                        .HasForeignKey("ReceiptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Receipt");
                });

            modelBuilder.Entity("Lamour.Domain.Entities.SalesOrder", b =>
                {
                    b.HasOne("Lamour.Domain.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Lamour.Domain.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Customer");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Lamour.Domain.Entities.SalesOrderLine", b =>
                {
                    b.HasOne("Lamour.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Lamour.Domain.Entities.SalesOrder", "SalesOrder")
                        .WithMany("Lines")
                        .HasForeignKey("SalesOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("SalesOrder");
                });

            modelBuilder.Entity("Lamour.Domain.Entities.SalesReturn", b =>
                {
                    b.HasOne("Lamour.Domain.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Lamour.Domain.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Customer");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Lamour.Domain.Entities.SalesReturnLine", b =>
                {
                    b.HasOne("Lamour.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Lamour.Domain.Entities.SalesReturn", "SalesReturn")
                        .WithMany("Lines")
                        .HasForeignKey("SalesReturnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("SalesReturn");
                });

            modelBuilder.Entity("Lamour.Domain.Entities.WarehouseReceipt", b =>
                {
                    b.HasOne("Lamour.Domain.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Lamour.Domain.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Customer");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Lamour.Domain.Entities.WarehouseReceiptLine", b =>
                {
                    b.HasOne("Lamour.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Lamour.Domain.Entities.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Lamour.Domain.Entities.WarehouseReceipt", "WarehouseReceipt")
                        .WithMany("Lines")
                        .HasForeignKey("WarehouseReceiptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Warehouse");

                    b.Navigation("WarehouseReceipt");
                });

            modelBuilder.Entity("Lamour.Domain.Entities.Payment", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("Lamour.Domain.Entities.Receipt", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("Lamour.Domain.Entities.SalesOrder", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Lamour.Domain.Entities.SalesReturn", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Lamour.Domain.Entities.WarehouseReceipt", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
