// <auto-generated />
using System;
using Lamour.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Lamour.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260426075209_AddCashTransactions")]
    partial class AddCashTransactions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Lamour.Domain.Entities.CashTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Account")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("account");

                    b.Property<DateTime>("AccountingDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accounting_date");

                    b.Property<string>("CounterAccount")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("counter_account");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("CreditAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("credit_amount");

                    b.Property<decimal>("DebitAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("debit_amount");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<DateTime>("DocumentDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("document_date");

                    b.Property<string>("PaymentNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("payment_number");

                    b.Property<string>("PersonName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("person_name");

                    b.Property<string>("ReceiptNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("receipt_number");

                    b.HasKey("Id");

                    b.HasIndex("AccountingDate");

                    b.ToTable("cash_transactions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Account = "111",
                            AccountingDate = new DateTime(2023, 11, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CounterAccount = "131",
                            CreatedAt = new DateTime(2023, 11, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreditAmount = 0m,
                            DebitAmount = 520000m,
                            Description = "Thu tiền khách hàng",
                            DocumentDate = new DateTime(2023, 11, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            PersonName = "Thanh Đức",
                            ReceiptNumber = "PT00678"
                        },
                        new
                        {
                            Id = 2,
                            Account = "111",
                            AccountingDate = new DateTime(2023, 11, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CounterAccount = "131",
                            CreatedAt = new DateTime(2023, 11, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreditAmount = 0m,
                            DebitAmount = 5850000m,
                            Description = "Thu tiền khách hàng",
                            DocumentDate = new DateTime(2023, 11, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            PersonName = "Thanh Đức",
                            ReceiptNumber = "PT00678"
                        },
                        new
                        {
                            Id = 3,
                            Account = "111",
                            AccountingDate = new DateTime(2023, 11, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CounterAccount = "131",
                            CreatedAt = new DateTime(2023, 11, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreditAmount = 0m,
                            DebitAmount = 5025000m,
                            Description = "Thu tiền khách hàng",
                            DocumentDate = new DateTime(2023, 11, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            PersonName = "Thanh Đức",
                            ReceiptNumber = "PT00678"
                        },
                        new
                        {
                            Id = 4,
                            Account = "111",
                            AccountingDate = new DateTime(2023, 11, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CounterAccount = "131",
                            CreatedAt = new DateTime(2023, 11, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreditAmount = 0m,
                            DebitAmount = 5640000m,
                            Description = "Thu tiền khách hàng",
                            DocumentDate = new DateTime(2023, 11, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            PersonName = "Thanh Đức",
                            ReceiptNumber = "PT00678"
                        },
                        new
                        {
                            Id = 5,
                            Account = "111",
                            AccountingDate = new DateTime(2023, 11, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CounterAccount = "131",
                            CreatedAt = new DateTime(2023, 11, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreditAmount = 0m,
                            DebitAmount = 5200000m,
                            Description = "Thu tiền khách hàng",
                            DocumentDate = new DateTime(2023, 11, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            PersonName = "Thanh Đức",
                            ReceiptNumber = "PT00678"
                        },
                        new
                        {
                            Id = 6,
                            Account = "111",
                            AccountingDate = new DateTime(2023, 11, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CounterAccount = "6418",
                            CreatedAt = new DateTime(2023, 11, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreditAmount = 615000m,
                            DebitAmount = 0m,
                            Description = "Diễm",
                            DocumentDate = new DateTime(2023, 11, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            PaymentNumber = "PC02215",
                            PersonName = "LÊ HOÀNG THANH ĐỨC"
                        },
                        new
                        {
                            Id = 7,
                            Account = "111",
                            AccountingDate = new DateTime(2023, 11, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CounterAccount = "6418",
                            CreatedAt = new DateTime(2023, 11, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreditAmount = 1055000m,
                            DebitAmount = 0m,
                            Description = "Thảo Uyên",
                            DocumentDate = new DateTime(2023, 11, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            PaymentNumber = "PC02215",
                            PersonName = "LÊ HOÀNG THANH ĐỨC"
                        },
                        new
                        {
                            Id = 8,
                            Account = "111",
                            AccountingDate = new DateTime(2023, 11, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CounterAccount = "6418",
                            CreatedAt = new DateTime(2023, 11, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreditAmount = 1228000m,
                            DebitAmount = 0m,
                            Description = "Phúc Nhi",
                            DocumentDate = new DateTime(2023, 11, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            PaymentNumber = "PC02215",
                            PersonName = "LÊ HOÀNG THANH ĐỨC"
                        },
                        new
                        {
                            Id = 9,
                            Account = "111",
                            AccountingDate = new DateTime(2023, 11, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CounterAccount = "6418",
                            CreatedAt = new DateTime(2023, 11, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreditAmount = 174000m,
                            DebitAmount = 0m,
                            Description = "Hân",
                            DocumentDate = new DateTime(2023, 11, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            PaymentNumber = "PC02215",
                            PersonName = "LÊ HOÀNG THANH ĐỨC"
                        },
                        new
                        {
                            Id = 10,
                            Account = "111",
                            AccountingDate = new DateTime(2023, 11, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CounterAccount = "6418",
                            CreatedAt = new DateTime(2023, 11, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreditAmount = 105000m,
                            DebitAmount = 0m,
                            Description = "Hương Ly",
                            DocumentDate = new DateTime(2023, 11, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            PaymentNumber = "PC02215",
                            PersonName = "LÊ HOÀNG THANH ĐỨC"
                        },
                        new
                        {
                            Id = 11,
                            Account = "111",
                            AccountingDate = new DateTime(2023, 11, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CounterAccount = "6418",
                            CreatedAt = new DateTime(2023, 11, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreditAmount = 450000m,
                            DebitAmount = 0m,
                            Description = "Mua like fanpage tháng 10/2023",
                            DocumentDate = new DateTime(2023, 11, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            PaymentNumber = "PC02216",
                            PersonName = "NGUYỄN HÀ THANH HÀ"
                        },
                        new
                        {
                            Id = 12,
                            Account = "111",
                            AccountingDate = new DateTime(2023, 11, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CounterAccount = "6418",
                            CreatedAt = new DateTime(2023, 11, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreditAmount = 1715000m,
                            DebitAmount = 0m,
                            Description = "Phí lưu kho t10/2023",
                            DocumentDate = new DateTime(2023, 11, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            PaymentNumber = "PC02217",
                            PersonName = "LÊ HOÀNG THANH ĐỨC"
                        },
                        new
                        {
                            Id = 13,
                            Account = "111",
                            AccountingDate = new DateTime(2023, 11, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CounterAccount = "6418",
                            CreatedAt = new DateTime(2023, 11, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreditAmount = 40000000m,
                            DebitAmount = 0m,
                            Description = "Thuê VP t11/2023",
                            DocumentDate = new DateTime(2023, 11, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            PaymentNumber = "PC02218",
                            PersonName = "LÊ HOÀNG THANH ĐỨC"
                        });
                });

            modelBuilder.Entity("Lamour.Domain.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("address");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<string>("CustomerGroup")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("customer_group");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("province");

                    b.Property<string>("TaxCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tax_code");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("customers", (string)null);
                });

            modelBuilder.Entity("Lamour.Domain.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BankAccountNumber")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("bank_account_number");

                    b.Property<string>("BankName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("bank_name");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("job_title")
                        .HasDefaultValueSql("'Khac'");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("unit")
                        .HasDefaultValueSql("'Spa'");

                    b.HasKey("Id");

                    b.ToTable("employees", (string)null);
                });

            modelBuilder.Entity("Lamour.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<decimal>("CostPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("cost_price");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<decimal>("SellingPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("selling_price");

                    b.Property<int>("StockQuantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("stock_quantity");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("unit");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasFilter("code <> ''");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("Lamour.Domain.Entities.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("address");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("group");

                    b.Property<bool>("IsStopTracking")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_stop_tracking");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<string>("TaxCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tax_code");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("suppliers", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
